const splashTexts = [
    "Moo!",
    "Missing something?",
    "Made by Notch!",
    "Reticulating Splines!",
    "Generating world...",
    "Loading terrain...",
    "Converting blocks...",
    "Updating textures...",
    "Creating biomes...",
    "Placing structures...",
    "Mining diamonds!",
    "Crafting tools...",
    "Planting trees...",
    "Spawning mobs...",
    "Building worlds...",
    "Programming logic...",
    "Connecting to server...",
    "Loading assets...",
    "Rendering chunks...",
    "Saving progress...",
    "Enhancing gameplay...",
    "Farming crops...",
    "Fishing for fun...",
    "Exploring caves...",
    "Adventuring...",
    "Climbing mountains...",
    "Sailing seas...",
    "Flying high...",
    "Lighting up...",
    "Fighting mobs...",
    "Crafting magic...",
    "Enchanting gear...",
    "Brewing potions...",
    "Building homes...",
    "Taming animals...",
    "Fighting dragons...",
    "Conquering dungeons...",
    "Trading with villagers...",
    "Collecting resources...",
    "Surviving nights...",
    "Exploring villages...",
    "Defeating bosses...",
    "Expanding territories...",
    "Protecting base...",
    "Harvesting crops...",
    "Breeding animals...",
    "Completing quests...",
    "Gathering XP...",
    "Training skills...",
    "Mastering combat...",
    "Creating redstone circuits...",
    "Building railways...",
    "Exploring mineshafts...",
    "Smelting ores...",
    "Forging weapons...",
    "Creating armor...",
    "Designing structures...",
    "Building monuments...",
    "Exploring strongholds...",
    "Finding secrets...",
    "Unlocking achievements...",
    "Exploring the Nether...",
    "Surviving the End...",
    "Conquering dimensions...",
    "Crafting ender chests...",
    "Finding elytra...",
    "Discovering new lands...",
    "Navigating oceans...",
    "Mapping the world...",
    "Exploring temples...",
    "Crafting beacons...",
    "Collecting trophies...",
    "Fighting withers...",
    "Building defenses...",
    "Mastering survival...",
    "Creating mods...",
    "Exploring dungeons...",
    "Gathering materials...",
    "Finding treasures...",
    "Exploring caves...",
    "Crafting ender pearls...",
    "Finding fortresses...",
    "Crafting fireworks...",
    "Exploring deserts...",
    "Fighting husks...",
    "Building skyscrapers...",
    "Mining deep...",
    "Exploring the abyss...",
    "Finding fossils...",
    "Crafting shields...",
    "Navigating swamps...",
    "Fighting witches...",
    "Building castles...",
    "Crafting boats...",
    "Exploring rivers...",
    "Navigating the seas...",
    "Finding shipwrecks...",
    "Exploring jungles...",
    "Crafting tridents...",
    "Exploring underwater caves...",
    "Finding underwater ruins...",
    "Building underwater bases...",
    "Creating conduits...",
    "Mastering the elements...",
    "Surviving hardcore mode...",
];
